import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/contexts/cart.context";
import ClientLayout from "@/components/ClientLayout";
import { Inter, Genos, Anta } from "next/font/google"; 
import { Suspense } from "react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const genos = Genos({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-genos",
});

const anta = Anta({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-anta",
});

export const metadata: Metadata = {
  title: "Orbis",
  description: "Generated by create next app",
  
  icons: {
    icon: "/favicon.svg", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${genos.variable} ${anta.variable} antialiased min-h-screen flex flex-col relative bg-[#070913]`}
      >
        <div className="relative z-10 flex-1 flex flex-col">
          <CartProvider>
                      <ClientLayout>
                          <Suspense fallback={<div className="w-full text-center pt-20 text-white">Loading...</div>}>
                              {children}
                          </Suspense>
                      </ClientLayout>
          </CartProvider>
        </div>
      </body>
    </html>
  );
}